logging:
  level:
    root: error
    com.mishinyura.booksrestapi: info
  file.name: logs/application.log

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  flyway:
    enabled: true
    locations: classpath:db/migration/h2
    sql-migration-prefix: H
    driver-class-name: org.h2.Driver

  security:
    user:
      name: user
      password: 1
